### PR TITLE
Prettier website

### PR DESCRIPTION
**Pull request by haselkern**
Having an attractive website with proper HTML means that users will be more interested in the content and that search engines will put the website higher in their results. I did not change a whole lot about the content, just made it a little nicer to look at, see the screenshot below. I'm open to suggestions!

Screenshot_2021-02-28 Rhai – Embedded Scripting for Rust

### CODE REVIEW

**Comment by schungx** [comment]
Wonderful!  The current website is woefully inadequate...  I have been waiting for somebody to put it into a reasonable single-page site, probably using some of the public templates...

This is a great first step.  At least now it is not ugly!

**Comment by schungx** [comment]
Now, to be greedy... can you actually make it into a nice project site?

**Comment by haselkern** [comment]
Im glad you like it :sweat_smile: Do you have anything specific in mind for the project site? I'm not quite sure what you would want on there.

**Comment by schungx** [comment]
Dunno... maybe something common to an open-source landing site?

Potentially with a blog... that someone will have time to write in the future!  ;-)

**Comment by haselkern** [comment]
Okay, I'll see what I can come up with! I will probably open a PR in the next few weeks.

**Pull request merged**
